# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c4e29c6bc0a8ca1a8c46f0761cbd1f273378a27d9f46efeb68282131ba8e2ec4de9e95e486c34a2ae4e59653d07be9d72b29a74eacb6d0827a74ddd87627d7

test:
  secret_key_base: cfd1853cd64e7236b07897ad48e6dbe3adf5b018b071c01d086a80f998eccad4fd08469ff516f3b5154448e4df24c98b03111cd4aac8eff9885a2e5573e6f346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
